# Generated by Django 4.2 on 2023-06-04 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookstoreModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Mystrey', 'Mystrey'), ('Thriller', 'Thriller'), ('Sci-Fi', 'Sci-Fi'), ('humor', 'Humor')], max_length=30)),
                ('first_publish', models.DateTimeField(auto_now_add=True)),
                ('last_publish', models.DateTimeField()),
            ],
        ),
    ]
