# Generated by Django 4.2 on 2023-06-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstoremodel',
            name='last_publish',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
